### ISSUE TITLE
analysis script has errors 

### ISSUE THREAD

**Issue by aberlin** [lordi/tickmate#82]
Hi, I tried to run the analysis script but it gives me this: 
`lib/python3.5/site-packages/pandas/core/missing.py", line 16, in _clean_fill_method
    method = method.lower()
AttributeError: 'int' object has no attribute 'lower'`

Testet it with
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)
 
I used the script a while ago I am not really deep into this, I guess it is a Problem with some updates in a dependency  

could you please specify for which versions the script is written ? 

Hope this helps

**Comment by lordi** [comment]
Thanks for the report, it should work with pandas 0.18 and python 3.x now.
Pandas had some breaking changes in 0.18.
